[tools]
bat = "latest"
eza = "latest"
fd = { version = "latest", os = ["linux", "macos/arm64"] }
fzf = "latest"
rg = "latest"
zoxide = "latest"
direnv = "latest"
watchexec = "latest"
usage = "latest"

buf = "latest"
go = "1.26.3"
node = "22.22.0"
uv = "latest"
atuin = { version = "latest", os = ["linux", "macos/arm64"] }
delta = "latest"

[settings]
experimental = true
lockfile = true
go_set_goroot = false

[settings.github]
credential_command = "gh auth token"
